### ISSUE TITLE
Add member invitations feature

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-social-network#21]
It may be desirable to limit new member registrations to reduce the likelihood of SPAM. One possible solution would be to allow users to invite friends to sign up for the network.

Add a feature to allow users to send invitations to encourage friends to sign up. Also, consider adding a setting that would toggle "invite-only" mode for the network, so administrators can choose whether to allow general access or make the network a bit more exclusive.

## Resources

- [django-invitations](https://github.com/bee-keeper/django-invitations)
- WagtailCMS - Site settings: [defining settings](https://docs.wagtail.io/en/v2.8.1/reference/contrib/settings.html)

**Comment by Upasanadhameliya** [comment]
Claim Issue

**Comment by Upasanadhameliya** [comment]
@brylie So based on your description I am assuming you want a link of invite friends as shown in the image.. upon clicking that link the user would be able to send an invite to their friends.. Am I right in my assumption? Please correct me or elaborate in my thought process..

![ques14](https://user-images.githubusercontent.com/28010398/129517140-a2fbe708-7c5b-4f90-a26f-f31bdbd8b4bd.png)

**Comment by Upasanadhameliya** [comment]
I made some progress on the same.. I installed the `django invitations` in the project, then tried to create page where a user can create invite and linked it to the home page.. I created custom form for getting the email input.. If you want to view my progress you can checkout the branch `(djinvitations)` on my fork of the repository.. Attaching screenshots of the progress

![ques15](https://user-images.githubusercontent.com/28010398/129562436-9a234801-8277-447f-ac50-58fff1cc3679.png)

![ques16](https://user-images.githubusercontent.com/28010398/129562459-4f8b5f9e-b2eb-497c-804d-8f176f9226d3.png)

![ques17](https://user-images.githubusercontent.com/28010398/129562484-28780e75-748d-4a50-b736-c922dacaa30b.png)

**Comment by brylie** [comment]
@Upasanadhameliya, very cool! Please go ahead and open a draft pull request to make it easier to review the changes. The draft pull request also indicates that the code is work-in-progress so it won't be merged by accident.

**Comment by brylie** [comment]
Also the `djinvitations` branch seems to be in your fork, so opening the draft pull request will make it easier for me to review the code.
