### ISSUE TITLE
Improve HomePage model

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-social-network#8]
The HomePage model came included with the fresh Wagtail installation. It could use a couple of improvements:

- add an `introduction` field
- add `max_count = 1`

**Comment by Upasanadhameliya** [comment]
Claim Issue

**Comment by brylie** [comment]
Hey thanks @Upasanadhameliya! I'll assign the issue to you.

**Comment by Upasanadhameliya** [comment]
@brylie do you want me to replace CharField with RichTextField? And also create migrations?

**Comment by brylie** [comment]
@Upasanadhameliya I reflected a bit and realized that your approach is perfect. I opened issue #15 as a continuation of this issue. Feel free to claim issue #15 if it seems interesting :-)
